Repository FakeItEasy/FakeItEasy, pull requests merged in 2019-09, with the labels that each got.

#1612 update build tools
  tools/Directory.Build.props
  tools/FakeItEasy.Build/FakeItEasy.Build.csproj
Labels: :gift: contribution

#1615 shorten input values in build logs
  tools/FakeItEasy.Build/Program.cs
Labels: :gift: contribution, build

#1616 Update PublicApiGenerator to 9.3.0
  tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
  tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
  tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd16.approved.txt
  tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd20.approved.txt
  tests/FakeItEasy.Tests.Approval/ApiApproval.cs
  tests/FakeItEasy.Tests.Approval/FakeItEasy.Tests.Approval.csproj
Labels: build

#1620 Pre-reduce nullable warnings
  src/FakeItEasy.Analyzer.Shared/ArgumentConstraintTypeMismatchCodeFixProvider.cs
  src/FakeItEasy.Analyzer.Shared/RepeatedAssertionCodeFixProvider.cs
  src/FakeItEasy/A.cs
  src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
  src/FakeItEasy/Core/CallRuleMetadata.cs
  src/FakeItEasy/Core/CallWriter.cs
  src/FakeItEasy/Core/FakeManager.AutoFakePropertyRule.cs
  src/FakeItEasy/Core/FakeManager.EventRule.cs
  src/FakeItEasy/Core/FakeManager.PropertyBehaviorRule.cs
  src/FakeItEasy/Core/FakeManager.PropertySetterRule.cs
  src/FakeItEasy/Core/FakeManager.cs
  src/FakeItEasy/Core/InterceptedFakeObjectCallExtensions.cs
  src/FakeItEasy/Creation/CreationResult.cs
  src/FakeItEasy/Creation/DummyValueResolver.cs
  src/FakeItEasy/Creation/FakeAndDummyManager.cs
  src/FakeItEasy/Creation/IFakeAndDummyManager.cs
  src/FakeItEasy/Creation/ResolvedArgument.cs
  src/FakeItEasy/Creation/ResolvedConstructor.cs
  src/FakeItEasy/Fake.of.T.cs
  src/FakeItEasy/RootModule.cs
  src/FakeItEasy/Sdk/Create.cs
  tests/FakeItEasy.Tests/ServiceLocatorTests.cs
Labels: :radioactive: tech-debt

#1621 Add unit test parentheses
  docs/quickstart.md
Labels: :gift: contribution, documentation

#1625 Protect out and ref parameters value producer
  src/FakeItEasy/Configuration/BuildableCallRule.cs
  src/FakeItEasy/Configuration/RuleBuilder.cs
  src/FakeItEasy/Expressions/ExpressionCallRule.cs
  tests/FakeItEasy.Tests/Configuration/BuildableCallRuleTests.cs
  tests/FakeItEasy.Tests/Configuration/RuleBuilderTests.cs
Labels: :hammer_and_wrench: refactoring

#1626 Simplify type checking in AnyCallRule
  src/FakeItEasy/Configuration/AnyCallCallRule.cs
  src/FakeItEasy/Configuration/AnyCallConfiguration.cs
  tests/FakeItEasy.Tests/Configuration/AnyCallConfigurationTests.cs
Labels: :hammer_and_wrench: refactoring
