Repository FakeItEasy/FakeItEasy, pull requests merged in 2023-04, with the labels that each got.

#1924 Provide placeholder names for anonymous parameters in received call descriptions
  src/FakeItEasy/Core/DefaultFakeObjectCallFormatter.cs
  tests/FakeItEasy.Specs/CallMatchingSpecs.cs
  tests/FakeItEasy.Specs/StrictFakeSpecs.cs
Labels: :rocket: enhancement

#1928 Ensure anonymous parameters are handled and displayed correctly in remaining cases
  src/FakeItEasy/MethodInfoExtensions.cs
  tests/FakeItEasy.Specs/ConfigurationSpecs.cs
  tests/FakeItEasy.Specs/CreationSpecs.cs
  tests/FakeItEasy.Tests.TestHelpers.FSharp/FakeItEasy.Tests.TestHelpers.FSharp.fsproj
  tests/FakeItEasy.Tests.TestHelpers.FSharp/IAmADelegateWithAnAnonymousParameter.fs
  tests/FakeItEasy.Tests.TestHelpers.FSharp/postbuild.ps1
  tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj
  tests/FakeItEasy.Tests/MethodInfoExtensionsTests.cs
Labels: :rocket: enhancement

#1936 Support net6.0 directly, dropping net5.0
  .github/workflows/ci.yml
  FakeItEasy.sln
  README.md
  how_to_build.md
  profiles/full.props
  profiles/net6.0.props
  profiles/netstandard2.0.props
  profiles/netstandard2.1.props
  src/FakeItEasy.Extensions.ValueTask/FakeItEasy.Extensions.ValueTask.csproj
  tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
  tests/FakeItEasy.Specs/IllegalFluentApiSpecs.cs
  tests/FakeItEasy.Tests.Approval/ApiApproval.cs
  tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net6.0.verified.txt
Labels: :rocket: enhancement, :scissors: removal

#1939 Publish docs preview
  .github/workflows/publish-docs-preview.yml
Labels: :building_construction: build
